PREFIX prolex: <https://example.org/prolexbase/ontology#>
SELECT ?type ?typeLabel (COUNT(DISTINCT ?pivot) AS ?numberOfEntities)
WHERE {
  ?pivot prolex:hasType ?type .
  OPTIONAL {
    ?type prolex:typeLabel ?typeLabel .
    FILTER(lang(?typeLabel) = "en")
  }
}
GROUP BY ?type ?typeLabel
ORDER BY DESC(?numberOfEntities)