PREFIX prolex: <https://example.org/prolexbase/ontology#>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>

SELECT ?pivot ?entry ?form ?derivative
WHERE {

  ?pivot prolex:hasType prolex:Type_27 .

  ?pivot prolex:hasLexicalEntry ?entry .

  ?entry ontolex:otherForm ?form .

  ?form prolex:formType "derivative" .

  ?form ontolex:writtenRep ?derivative .

  FILTER(lang(?derivative) = "ar")
}
LIMIT 50