PREFIX prolex: <https://example.org/prolexbase/ontology#>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>

SELECT ?wholePivot ?wholeName ?meronymPivot ?meronymName
WHERE {

  VALUES ?wholePivot { prolex:Pivot_45530 }

  ?wholePivot prolex:hasMeronym ?meronymPivot .

  # nom anglais du pivot principal
  ?wholePivot prolex:hasLexicalEntry ?entry1 .
  ?entry1 ontolex:canonicalForm ?form1 .
  ?form1 ontolex:writtenRep ?wholeName .

  FILTER(lang(?wholeName) = "en")

  # nom anglais du méronyme
  ?meronymPivot prolex:hasLexicalEntry ?entry2 .
  ?entry2 ontolex:canonicalForm ?form2 .
  ?form2 ontolex:writtenRep ?meronymName .

  FILTER(lang(?meronymName) = "en")
}