PREFIX prolex: <https://example.org/prolexbase/ontology#>
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>

SELECT (COUNT(?form) AS ?numberOfDerivatives)
WHERE {
  ?entry ontolex:otherForm ?form .
  ?form prolex:formType "derivative" .
}